version: '3.7'
services:

  db:
    image: mysql
    container_name: dbtest
    restart: always
    networks:
      - backend
    environment:
      MYSQL_DATABASE: blogger
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db_store:/var/lib/mysql
      - ./data/blogger.sql:/docker-entrypoint-initdb.d/blogger.sql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    networks:
      - backend
    ports:
      - 8080:80
    environment:
      - PMA_HOST=dbtest

  phpfpm:
    container_name: phpfpm
    restart: always
    image: nanoninja/php-fpm:8.1
    networks:
      - backend
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    command: php -S="0.0.0.0:3000" -t="/var/www/html/web"

networks:
  backend:
    driver: bridge

volumes:
  db_store: